#!/bin/bash
# postinst script for opx-core
#
# Update the version information for opx-show-version
#
# see: dh_installdeb(1)

set -e

case "$1" in

    configure)
        # Update the version information
        FILE="/etc/OPX-release-version"
        OS_VERSION="3.0.0"
        INSTALL_DATE=$(date +'%Y-%m-%dT%H:%M:%S%z')

        if [ -f $FILE ]
        then
            sed -i "s/^OS_VERSION=.*$/OS_VERSION=${OS_VERSION}/" $FILE
            sed -i "s/^INSTALL_DATE=.*$/INSTALL_DATE=${INSTALL_DATE}/" $FILE
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0;
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1;
    ;;
esac

exit 0

